name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '34 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/devbuild.yml
      - uses: ./.github/workflows/nouse_install.yml
      - uses: ./.github/workflows/lint.yml
      - uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/artifacts


      